### PR TITLE
second set of tests added to prove rename is working correctly

### PR DESCRIPTION
**Pull request by kpartlow**

### CODE REVIEW

**Comment by jdereg** [comment]
I can demonstrate this everytime.

I delete my branch, copy HEAD, and then begin the test.  I rename
buzz.adjective to buzz.adj, commit, then rename it back, and it won't
commit.

Also, the variation on the above without the intervening commit fails.

**Comment by kpartlow** [comment]
Is your head cube one of the ones that is us on with types?

**Comment by kpartlow** [comment]
Try it with newly created cubes instead of your old data

**Comment by jdereg** [comment]
No, the HEAD cube (buzz.adjective) is a regular cube (not an old-serialized
cube).

**Pull request merged**
